import type { zInfer } from "@/types/common";
import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { z } from "zod";

const ALGORITHM = "aes-256-gcm";
const IV_SIZE = 12;

const EncryptionPayload = z.object({
  algorithm: z.literal(ALGORITHM),
  ivEncoded: z.string(),
  authTagEncoded: z.string(),
  encryptedEncoded: z.string(),
});
type EncryptionPayload = zInfer<typeof EncryptionPayload>;

/**
 * Encryption key is generated by `openssl rand -hex 32` command.
 */
export class Encryptor {
  #encryptionKey: Buffer;

  constructor(encryptionKey: string) {
    if (!encryptionKey) {
      throw new Error("Encryption key string must exist.");
    }

    if (encryptionKey.length !== 64) {
      throw new Error("Encryption key string length must be 64.");
    }

    const buffer = Buffer.from(encryptionKey, "hex");
    if (buffer.length !== 32) {
      throw new Error("Encryption key buffer length must be 32.");
    }

    this.#encryptionKey = buffer;
  }

  encrypt(text: string) {
    const iv = randomBytes(IV_SIZE);
    const algorithm = ALGORITHM;
    const cipher = createCipheriv(algorithm, this.#encryptionKey, iv);
    const encrypted = Buffer.concat([
      cipher.update(text, "utf8"),
      cipher.final(),
    ]);
    const authTag = cipher.getAuthTag();
    const payload = {
      algorithm,
      ivEncoded: iv.toString("base64"),
      authTagEncoded: authTag.toString("base64"),
      encryptedEncoded: encrypted.toString("base64"),
    } satisfies EncryptionPayload;
    const payloadString = JSON.stringify(payload);
    const payloadEncoded = Buffer.from(payloadString).toString("base64");
    return payloadEncoded;
  }

  decrypt(payloadEncoded: string) {
    try {
      return this.#decrypt(payloadEncoded);
    } catch (e) {
      console.error("Decryption failed. error:", e);
      throw new Error("Decryption failed.");
    }
  }

  #decrypt(payloadEncoded: string) {
    const payloadString = Buffer.from(payloadEncoded, "base64").toString(
      "utf8"
    );
    const payloadRaw = JSON.parse(payloadString);
    const payload = EncryptionPayload.parse(payloadRaw);
    const { algorithm } = payload;
    const iv = Buffer.from(payload.ivEncoded, "base64");
    const authTag = Buffer.from(payload.authTagEncoded, "base64");
    const encrypted = Buffer.from(payload.encryptedEncoded, "base64");
    const decipher = createDecipheriv(algorithm, this.#encryptionKey, iv);
    decipher.setAuthTag(authTag);
    const textBuffer = Buffer.concat([
      decipher.update(encrypted),
      decipher.final(),
    ]);
    const text = textBuffer.toString("utf8");
    return text;
  }
}
