name: Deploy to AWS EB

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install EB CLI
        run: |
          pip install awsebcli==3.23.3
          eb --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::003342497027:role/github-withsy-chat-deploy
          aws-region: us-east-2

      - name: Get Dotenv Contents
        run: |
          VALUE=$(aws ssm get-parameter --name withsy-chat-prod --with-decryption --region us-east-2 --query "Parameter.Value" --output text)
          echo "$VALUE" >> .env
          cat .env | cut -c 1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to EB
        run: |
          eb deploy withsy-chat-env --label "version-${{ github.sha }}"
