name: Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::003342497027:role/github-withsy-secret
          aws-region: us-east-2

      - name: Get Dotenv Contents
        run: |
          VALUE=$(aws ssm get-parameter --name production --with-decryption --region us-east-2 --query "Parameter.Value" --output text)
          echo "DOTENV_CONTENTS<<EOF" >> $GITHUB_ENV
          echo "$VALUE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "$VALUE" | cut -c 1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          TAG=003342497027.dkr.ecr.us-east-2.amazonaws.com/withsy/withsy-chat:latest
          docker build --tag "$TAG" --secret id=DOTENV_CONTENTS,env=DOTENV_CONTENTS -f prod/Dockerfile .
          docker push "$TAG"
